# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96b25aedf5eac70592cd8d694e92b3d61d35629187decb41bb4467d85d493f759d9fa1665edae135a0523d3d033c6f18b84179ff38d4a200841cc8eac0a4dba1

test:
  secret_key_base: ca6195aa23dc8670d5b4eeeb645fd47654022a99636a5b0829eeb40e3921bf34d400aab9a07e1615f2ffd47d59f8281684f606c2e57bae323ee23a105f1cdfec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
